//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagement
    {
        public int UId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public int UserRoleId { get; set; }
        public int UserReignsId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CBY { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBY { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual Reign Reign { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
